Mayhem integration
mayhemheroes/smoltcp pull request #1
Opened 2022-04-26 02:24 UTC by Verylostpenguin

2022-04-27 12:11 UTC, nathanjackson requested changes
Thanks for your PR.

See my comments, there are a few things we need to have fixed before we can merge this.

2022-04-27 12:11 UTC, nathanjackson commented on Mayhemfile
> +  - cmd: /smoltcp/fuzz/target/x86_64-unknown-linux-gnu/release/dhcp_header
Similar to your other PR. We need changes to your Mayhemfile.

- Remove your username from the project.
- No need to include duration.
- Please remove all but one cmd and rename the target field to reflect it. Mayhemfiles should be written for one target, but the multiple commands listed here would actually be for multiple targets.

2022-04-29 01:27 UTC, Verylostpenguin commented on Mayhemfile
> +  - cmd: /smoltcp/fuzz/target/x86_64-unknown-linux-gnu/release/dhcp_header
I've deleted the username and duration from the mayhemfile. I also created multiple mayhem files which I run in the yml file sequentially. I hope this addresses all the issues listed above.

2022-05-03 01:54 UTC, nathanjackson approved these changes
Looks good to me.

2022-05-03 01:54 UTC, merged

2022-05-03 17:56 UTC, nathanjackson commented
@Verylostpenguin Thanks for your integration, someone should be reaching out to you about the $750 payment.

I am going to turn on automatic updates to this repo. Please keep an eye on this repo to ensure the Mayhem action continues to work. If something breaks within the next 30 days, we'll look to you to fix it for the last $250 on this submission.